(defun music(filename)
  (interactive "sWhat to play?: ")
  (call-process-shell-command (concat "cvlc --play-and-exit " filename) nil 0)
)
(defun nomusic()
  (interactive)
  (call-process-shell-command "killall vlc" nil 0)
)
(defun gimmeradio()
  (interactive)
  (call-process-shell-command "cvlc --play-and-exit https://gimme-stream.s3-us-west-1.amazonaws.com/128k/gimme1_aac_128.m3u8" nil 0)
)

(defun volume-up()
  (interactive)
  (shell-command "amixer -q sset Master 5%+")
)
(defun volume-down()
  (interactive)
  (shell-command "amixer -q sset Master 5%-")
)
(defun volume-set(num)
  (interactive "sVolume:")
  (shell-command (concat "amixer -q sset Master " num "%"))
)

(global-set-key (kbd "C-c +") 'volume-up)
(global-set-key (kbd "C-c -") 'volume-down)

(provide 'emacs-music)
